/**
 * Parameter Inspector - Shows all params used per step with seed chain visualization
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Copy, Key, Fingerprint, Settings2, Shuffle } from 'lucide-react';
import { toast } from 'sonner';

interface StepData {
  operation: string;
  params?: Record<string, any>;
  seed?: string;
}

interface ParameterInspectorProps {
  steps: StepData[];
  currentStep: number;
  seedChain?: string[];
}

export const ParameterInspector = ({
  steps,
  currentStep,
  seedChain,
}: ParameterInspectorProps) => {
  const step = steps[currentStep];
  const prevStep = currentStep > 0 ? steps[currentStep - 1] : null;

  const copyParams = () => {
    if (step?.params) {
      navigator.clipboard.writeText(JSON.stringify(step.params, null, 2));
      toast.success('Parameters copied to clipboard');
    }
  };

  const isAutoGenerated = (key: string, value: any): boolean => {
    if (key === 'seed') return !steps[currentStep]?.params?.seed;
    if (key === 'mask' && typeof value === 'string' && value.length > 0) {
      // Check if alternating pattern (auto-generated default)
      const isAlternating = /^(10)+1?$|^(01)+0?$/.test(value);
      return isAlternating;
    }
    return false;
  };

  const getParamDiff = (key: string): 'new' | 'changed' | 'same' | 'removed' => {
    if (!prevStep?.params) return 'new';
    if (!(key in (prevStep.params || {}))) return 'new';
    if (JSON.stringify(prevStep.params[key]) !== JSON.stringify(step?.params?.[key])) return 'changed';
    return 'same';
  };

  if (!step) {
    return (
      <div className="text-center py-8 text-muted-foreground">
        <Settings2 className="w-12 h-12 mx-auto mb-4 opacity-50" />
        <p>Select a step to inspect parameters</p>
      </div>
    );
  }

  const params = step.params || {};
  const paramEntries = Object.entries(params);

  return (
    <div className="space-y-4">
      {/* Current Step Header */}
      <Card>
        <CardContent className="py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="text-xs">Step #{currentStep + 1}</Badge>
              <Badge className="bg-primary/20 text-primary text-xs">{step.operation}</Badge>
            </div>
            <Button variant="ghost" size="sm" onClick={copyParams}>
              <Copy className="w-3 h-3 mr-1" />
              Copy
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Parameters */}
      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Key className="w-4 h-4" />
            Parameters ({paramEntries.length})
          </CardTitle>
        </CardHeader>
        <CardContent className="py-2">
          {paramEntries.length === 0 ? (
            <p className="text-xs text-muted-foreground text-center py-4">No parameters</p>
          ) : (
            <div className="space-y-2">
              {paramEntries.map(([key, value]) => {
                const auto = isAutoGenerated(key, value);
                const diff = getParamDiff(key);
                const displayValue = typeof value === 'string' && value.length > 64
                  ? value.slice(0, 32) + '...' + value.slice(-16) + ` (${value.length} chars)`
                  : JSON.stringify(value);

                return (
                  <div key={key} className={`p-2 rounded border text-xs ${
                    diff === 'changed' ? 'border-yellow-500/30 bg-yellow-500/5' :
                    diff === 'new' ? 'border-primary/30 bg-primary/5' :
                    'border-border bg-muted/20'
                  }`}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-mono font-medium">{key}</span>
                      <div className="flex items-center gap-1">
                        {auto && (
                          <Badge variant="secondary" className="text-xs px-1 py-0">
                            <Shuffle className="w-2 h-2 mr-0.5" />
                            auto
                          </Badge>
                        )}
                        {!auto && key === 'mask' && (
                          <Badge className="bg-blue-500/20 text-blue-400 text-xs px-1 py-0">manual</Badge>
                        )}
                        {diff === 'changed' && (
                          <Badge variant="outline" className="text-yellow-500 text-xs px-1 py-0">changed</Badge>
                        )}
                        {diff === 'new' && (
                          <Badge variant="outline" className="text-primary text-xs px-1 py-0">new</Badge>
                        )}
                      </div>
                    </div>
                    <code className="text-muted-foreground break-all">{displayValue}</code>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Seed Chain */}
      {seedChain && seedChain.length > 0 && (
        <Card>
          <CardHeader className="py-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <Fingerprint className="w-4 h-4" />
              Seed Chain ({seedChain.length})
            </CardTitle>
          </CardHeader>
          <CardContent className="py-2">
            <ScrollArea className="h-[200px]">
              <div className="space-y-1">
                {seedChain.map((seed, idx) => (
                  <div
                    key={idx}
                    className={`flex items-center gap-2 p-1.5 rounded text-xs font-mono ${
                      idx === currentStep ? 'bg-primary/10 border border-primary/30' : 'hover:bg-muted/30'
                    }`}
                  >
                    <span className="text-muted-foreground w-6">#{idx + 1}</span>
                    <code className="truncate flex-1">{seed}</code>
                    {idx === currentStep && (
                      <Badge variant="default" className="text-xs px-1 py-0">current</Badge>
                    )}
                  </div>
                ))}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      )}

      {/* Mask Visualization */}
      {params.mask && typeof params.mask === 'string' && (
        <Card>
          <CardHeader className="py-3">
            <CardTitle className="text-sm">Mask Pattern</CardTitle>
          </CardHeader>
          <CardContent className="py-2">
            <div className="flex flex-wrap gap-px">
              {params.mask.slice(0, 128).split('').map((bit: string, i: number) => (
                <div
                  key={i}
                  className={`w-2 h-4 ${bit === '1' ? 'bg-primary' : 'bg-muted/30'}`}
                  title={`Bit ${i}: ${bit}`}
                />
              ))}
            </div>
            {params.mask.length > 128 && (
              <p className="text-xs text-muted-foreground mt-1">
                Showing first 128 of {params.mask.length} bits
              </p>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};
